compatibility_date: "2026-09-13"
build: {}
docker:
    php:
        version: "8.5"
environments:
    local:
        type: docker
        url: https://shopware67.shopware.local
        admin_api:
            username: admin
            password: shopware
